// Deletes ALL existing entries
exports.seed = function (knex) {
        return knex('airman').del()
            .then(function () {
                // Inserts seed entries
                return knex('airman').insert([
                    {
                        first_name: 'Bob',
                        last_name: 'Dylan',
                        middle_initial: "F",
                        rank_id: 3,
                        squadron: '12IS',
                        flight: 'ABC',
                        afsc: '1NX51A',
                        deros: 20210317,
                        bio: 'I love turtles and sand.',
                        airman_photo_url: "imageurl"
                    },
                    {
                        first_name: 'Robert',
                        last_name: 'Zimmerman',
                        middle_initial: "Q",
                        rank_id: 5,
                        squadron: '12IS',
                        flight: 'ABD',
                        afsc: '1NX51A',
                        deros: 20230612,
                        bio: 'Blonde on Blonde.',
                        airman_photo_url: "imageurl"
                    },
                    {
                        first_name: 'OJ',
                        last_name: 'Simpson',
                        middle_initial: "R",
                        rank_id: 3,
                        squadron: '12IS',
                        flight: 'FDS',
                        afsc: '1N351B',
                        deros: 20210517,
                        bio: 'I didnt do it',
                        airman_photo_url: "imageurl",
                    },
                    {
                        first_name: 'Frank',
                        last_name: 'Sinatra',
                        middle_initial: "F",
                        rank_id: 7,
                        squadron: '12IS',
                        flight: 'DOP',
                        afsc: '1N551B',
                        deros: 20220517,
                        bio: 'I can sing',
                        airman_photo_url: "imageurl",
                    },
                    {
                        first_name: 'Terry',
                        last_name: 'Larry',
                        middle_initial: "D",
                        rank_id: 7,
                        squadron: '12IS',
                        flight: 'FGE',
                        afsc: '1N751B',
                        deros: 20210517,
                        bio: 'I run really fast',
                        airman_photo_url: "imageurl",
                    },
                    {
                        first_name: 'Chuck',
                        last_name: 'Norris',
                        middle_initial: "A",
                        rank_id: 2,
                        squadron: '12IS',
                        flight: 'FGR',
                        afsc: '1N051B',
                        deros: 20220517,
                        bio: 'Ill fight you with a cowboy hat on',
                        airman_photo_url: "imageurl",
                    },
                    {
                        first_name: 'Elon',
                        last_name: 'Musk',
                        middle_initial: "F",
                        rank_id: 7,
                        squadron: '12IS',
                        flight: 'ABC',
                        afsc: '1N351B',
                        deros: 20210517,
                        bio: 'I love volunteering',
                        airman_photo_url: "imageurl",
                    },
                    {
                        first_name: 'John',
                        last_name: 'Snow',
                        middle_initial: "G",
                        rank_id: 7,
                        squadron: '12IS',
                        flight: 'ABC',
                        afsc: '1N251B',
                        deros: 20210117,
                        bio: 'Im from the north',
                        airman_photo_url: "imageurl",
                    },
                    {
                        first_name: 'George',
                        last_name: 'Myers',
                        middle_initial: "P",
                        rank_id: 3,
                        squadron: '12IS',
                        flight: 'RFE',
                        afsc: '1N651B',
                        deros: 20220517,
                        bio: 'Im king of the jungle',
                        airman_photo_url: "imageurl",
                    },
                    {
                        first_name: 'Bart',
                        last_name: 'Simpson',
                        middle_initial: "D",
                        rank_id: 5,
                        squadron: '12IS',
                        flight: 'FGL',
                        afsc: '1N151B',
                        deros: 20210917,
                        bio: 'oh man',
                        airman_photo_url: "imageurl",
                    },
                    {
                        first_name: 'Mariah',
                        last_name: 'Carrey',
                        middle_initial: "C",
                        rank_id: 7,
                        squadron: '12IS',
                        flight: 'FGE',
                        afsc: '1N451B',
                        deros: 20210517,
                        bio: 'ALL I want for christmas is YOU',
                        airman_photo_url: "imageurl",
                    },
                    {
                        first_name: 'Jim',
                        last_name: 'Carrey',
                        middle_initial: "H",
                        rank_id: 2,
                        squadron: '12IS',
                        flight: 'RPE',
                        afsc: '1N351B',
                        deros: 20200517,
                        bio: 'Are you telling me theres a chance?',
                        airman_photo_url: "imageurl",
                    },
                    {
                        first_name: 'Keanu',
                        last_name: 'Sulon',
                        middle_initial: "K",
                        rank_id: 2,
                        squadron: '12IS',
                        flight: 'ABR',
                        afsc: '1N351B',
                        deros: 20200513,
                        bio: 'Im adorable',
                        airman_photo_url: "imageurl",
                    },
                    {
                        first_name: 'Harry',
                        last_name: 'Potter',
                        middle_initial: "F",
                        rank_id: 4,
                        squadron: '12IS',
                        flight: 'ABC',
                        afsc: '1N851B',
                        deros: 20210717,
                        bio: 'Snape is my favorite teacher',
                        airman_photo_url: "imageurl",
                    },
                ]);
            });
}